name: michele_s_application8
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.5
  flutter_dotenv: ^5.0.2
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  flutter_switch: ^0.3.2
  intl: ^0.17.0
  file: ^6.1.4
  dots_indicator: ^2.0.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: "^0.12.0"
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/CookingLab-Top.jpg
    - assets/images/logo_a_fa.png
    - assets/images/img_rectangle286.png
    - assets/images/img1.png
    - assets/images/img2.png
    - assets/images/img3.png
    - assets/images/img_image1.png
    - assets/images/foto-CookingLab.jpeg
    - assets/images/lab1.jpg
    - assets/images/lab2.jpg
    - assets/images/lab3.jpg
    - .env
  fonts: 
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoRomanLight.ttf
          weight: 300
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_a_fa.png"

